### ISSUE TITLE
[TO-DO] Explore - DevTools Diagramming

### ISSUE THREAD

**Issue by oodball** [oodball/sp24-cse110-lab4#10]
## Major Task - minor task
- [ ] create flowchart
- [ ] enter website
- [ ] add search or explore options
- [ ] product options
- [ ] continue shopping options
- [ ] view cart
- [ ] view payment
- [ ] confirmation page, email
